# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pierre/Programming/C++_Projects/ImgurFetch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pierre/Programming/C++_Projects/ImgurFetch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Programming/C++_Projects/ImgurFetch/CMakeFiles /home/pierre/Programming/C++_Projects/ImgurFetch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pierre/Programming/C++_Projects/ImgurFetch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named imgurfetch

# Build rule for target.
imgurfetch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgurfetch
.PHONY : imgurfetch

# fast build rule for target.
imgurfetch/fast:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/build
.PHONY : imgurfetch/fast

src/Downloader.o: src/Downloader.cpp.o

.PHONY : src/Downloader.o

# target to build an object file
src/Downloader.cpp.o:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/Downloader.cpp.o
.PHONY : src/Downloader.cpp.o

src/Downloader.i: src/Downloader.cpp.i

.PHONY : src/Downloader.i

# target to preprocess a source file
src/Downloader.cpp.i:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/Downloader.cpp.i
.PHONY : src/Downloader.cpp.i

src/Downloader.s: src/Downloader.cpp.s

.PHONY : src/Downloader.s

# target to generate assembly for a file
src/Downloader.cpp.s:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/Downloader.cpp.s
.PHONY : src/Downloader.cpp.s

src/HTTPRequest.o: src/HTTPRequest.cpp.o

.PHONY : src/HTTPRequest.o

# target to build an object file
src/HTTPRequest.cpp.o:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/HTTPRequest.cpp.o
.PHONY : src/HTTPRequest.cpp.o

src/HTTPRequest.i: src/HTTPRequest.cpp.i

.PHONY : src/HTTPRequest.i

# target to preprocess a source file
src/HTTPRequest.cpp.i:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/HTTPRequest.cpp.i
.PHONY : src/HTTPRequest.cpp.i

src/HTTPRequest.s: src/HTTPRequest.cpp.s

.PHONY : src/HTTPRequest.s

# target to generate assembly for a file
src/HTTPRequest.cpp.s:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/HTTPRequest.cpp.s
.PHONY : src/HTTPRequest.cpp.s

src/SSL_Handler.o: src/SSL_Handler.cpp.o

.PHONY : src/SSL_Handler.o

# target to build an object file
src/SSL_Handler.cpp.o:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/SSL_Handler.cpp.o
.PHONY : src/SSL_Handler.cpp.o

src/SSL_Handler.i: src/SSL_Handler.cpp.i

.PHONY : src/SSL_Handler.i

# target to preprocess a source file
src/SSL_Handler.cpp.i:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/SSL_Handler.cpp.i
.PHONY : src/SSL_Handler.cpp.i

src/SSL_Handler.s: src/SSL_Handler.cpp.s

.PHONY : src/SSL_Handler.s

# target to generate assembly for a file
src/SSL_Handler.cpp.s:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/SSL_Handler.cpp.s
.PHONY : src/SSL_Handler.cpp.s

src/epubCompiler.o: src/epubCompiler.cpp.o

.PHONY : src/epubCompiler.o

# target to build an object file
src/epubCompiler.cpp.o:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/epubCompiler.cpp.o
.PHONY : src/epubCompiler.cpp.o

src/epubCompiler.i: src/epubCompiler.cpp.i

.PHONY : src/epubCompiler.i

# target to preprocess a source file
src/epubCompiler.cpp.i:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/epubCompiler.cpp.i
.PHONY : src/epubCompiler.cpp.i

src/epubCompiler.s: src/epubCompiler.cpp.s

.PHONY : src/epubCompiler.s

# target to generate assembly for a file
src/epubCompiler.cpp.s:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/epubCompiler.cpp.s
.PHONY : src/epubCompiler.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/imgurfetch.dir/build.make CMakeFiles/imgurfetch.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... imgurfetch"
	@echo "... edit_cache"
	@echo "... src/Downloader.o"
	@echo "... src/Downloader.i"
	@echo "... src/Downloader.s"
	@echo "... src/HTTPRequest.o"
	@echo "... src/HTTPRequest.i"
	@echo "... src/HTTPRequest.s"
	@echo "... src/SSL_Handler.o"
	@echo "... src/SSL_Handler.i"
	@echo "... src/SSL_Handler.s"
	@echo "... src/epubCompiler.o"
	@echo "... src/epubCompiler.i"
	@echo "... src/epubCompiler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

